#![allow(unused)]
#[derive(Default, Debug)]
pub enum BaliseSVG {
    A,
    AltGlyph,
    AltGlyphDef,
    AltGlyphItem,
    Animate,
    AnimateMotion,
    AnimateTransform,
    Circle,
    ClipPath,
    ColorProfile,
    Cursor,
    Defs,
    Desc,
    Ellipse,
    FeBlend,
    FeColorMatrix,
    FeComponentTransfer,
    FeComposite,
    FeConvolveMatrix,
    FeDiffuseLighting,
    FeDisplacementMap,
    FeDistantLight,
    FeFlood,
    FeFuncA,
    FeFuncB,
    FeFuncG,
    FeFuncR,
    FeGaussianBlur,
    FeImage,
    FeMerge,
    FeMergeNode,
    FeMorphology,
    FeOffset,
    FePointLight,
    FeSpecularLighting,
    FeSpotLight,
    FeTile,
    FeTurbulence,
    Filter,
    Font,
    FontFace,
    FontFaceFormat,
    FontFaceName,
    FontFaceSrc,
    FontFaceUri,
    ForeignObject,
    G,
    Glyph,
    GlyphRef,
    Hkern,
    Image,
    Line,
    LinearGradient,
    Marker,
    Mask,
    Metadata,
    MissingGlyph,
    Mpath,
    Path,
    Pattern,
    Polygon,
    Polyline,
    RadialGradient,
    Rect,
    Script,
    Set,
    Stop,
    Style,
    Svg,
    Switch,
    Symbol,
    Text,
    TextPath,
    Title,
    Tref,
    Tspan,
    Use,
    View,
    Vkern,
    #[default]
    Other,
}

impl BaliseSVG {
    pub fn name(&self) -> Option<String> {
        match self {
            BaliseSVG::A => Some(String::from("a")),
            BaliseSVG::AltGlyph => Some(String::from("altGlyph")),
            BaliseSVG::AltGlyphDef => Some(String::from("altGlyphDef")),
            BaliseSVG::AltGlyphItem => Some(String::from("altGlyphItem")),
            BaliseSVG::Animate => Some(String::from("animate")),
            BaliseSVG::AnimateMotion => Some(String::from("animateMotion")),
            BaliseSVG::AnimateTransform => Some(String::from("animateTransform")),
            BaliseSVG::Circle => Some(String::from("circle")),
            BaliseSVG::ClipPath => Some(String::from("clipPath")),
            BaliseSVG::ColorProfile => Some(String::from("color-profile")),
            BaliseSVG::Cursor => Some(String::from("cursor")),
            BaliseSVG::Defs => Some(String::from("defs")),
            BaliseSVG::Desc => Some(String::from("desc")),
            BaliseSVG::Ellipse => Some(String::from("ellipse")),
            BaliseSVG::FeBlend => Some(String::from("feBlend")),
            BaliseSVG::FeColorMatrix => Some(String::from("feColorMatrix")),
            BaliseSVG::FeComponentTransfer => Some(String::from("feComponentTransfer")),
            BaliseSVG::FeComposite => Some(String::from("feComposite")),
            BaliseSVG::FeConvolveMatrix => Some(String::from("feConvolveMatrix")),
            BaliseSVG::FeDiffuseLighting => Some(String::from("feDiffuseLighting")),
            BaliseSVG::FeDisplacementMap => Some(String::from("feDisplacementMap")),
            BaliseSVG::FeDistantLight => Some(String::from("feDistantLight")),
            BaliseSVG::FeFlood => Some(String::from("feFlood")),
            BaliseSVG::FeFuncA => Some(String::from("feFuncA")),
            BaliseSVG::FeFuncB => Some(String::from("feFuncB")),
            BaliseSVG::FeFuncG => Some(String::from("feFuncG")),
            BaliseSVG::FeFuncR => Some(String::from("feFuncR")),
            BaliseSVG::FeGaussianBlur => Some(String::from("feGaussianBlur")),
            BaliseSVG::FeImage => Some(String::from("feImage")),
            BaliseSVG::FeMerge => Some(String::from("feMerge")),
            BaliseSVG::FeMergeNode => Some(String::from("feMergeNode")),
            BaliseSVG::FeMorphology => Some(String::from("feMorphology")),
            BaliseSVG::FeOffset => Some(String::from("feOffset")),
            BaliseSVG::FePointLight => Some(String::from("fePointLight")),
            BaliseSVG::FeSpecularLighting => Some(String::from("feSpecularLighting")),
            BaliseSVG::FeSpotLight => Some(String::from("feSpotLight")),
            BaliseSVG::FeTile => Some(String::from("feTile")),
            BaliseSVG::FeTurbulence => Some(String::from("feTurbulence")),
            BaliseSVG::Filter => Some(String::from("filter")),
            BaliseSVG::Font => Some(String::from("font")),
            BaliseSVG::FontFace => Some(String::from("font-face")),
            BaliseSVG::FontFaceFormat => Some(String::from("font-face-format")),
            BaliseSVG::FontFaceName => Some(String::from("font-face-name")),
            BaliseSVG::FontFaceSrc => Some(String::from("font-face-src")),
            BaliseSVG::FontFaceUri => Some(String::from("font-face-uri")),
            BaliseSVG::ForeignObject => Some(String::from("foreignObject")),
            BaliseSVG::G => Some(String::from("g")),
            BaliseSVG::Glyph => Some(String::from("glyph")),
            BaliseSVG::GlyphRef => Some(String::from("glyphRef")),
            BaliseSVG::Hkern => Some(String::from("hkern")),
            BaliseSVG::Image => Some(String::from("image")),
            BaliseSVG::Line => Some(String::from("line")),
            BaliseSVG::LinearGradient => Some(String::from("linearGradient")),
            BaliseSVG::Marker => Some(String::from("marker")),
            BaliseSVG::Mask => Some(String::from("mask")),
            BaliseSVG::Metadata => Some(String::from("metadata")),
            BaliseSVG::MissingGlyph => Some(String::from("missing-glyph")),
            BaliseSVG::Mpath => Some(String::from("mpath")),
            BaliseSVG::Path => Some(String::from("path")),
            BaliseSVG::Pattern => Some(String::from("pattern")),
            BaliseSVG::Polygon => Some(String::from("polygon")),
            BaliseSVG::Polyline => Some(String::from("polyline")),
            BaliseSVG::RadialGradient => Some(String::from("radialGradient")),
            BaliseSVG::Rect => Some(String::from("rect")),
            BaliseSVG::Script => Some(String::from("script")),
            BaliseSVG::Set => Some(String::from("set")),
            BaliseSVG::Stop => Some(String::from("stop")),
            BaliseSVG::Style => Some(String::from("style")),
            BaliseSVG::Svg => Some(String::from("svg")),
            BaliseSVG::Switch => Some(String::from("switch")),
            BaliseSVG::Symbol => Some(String::from("symbol")),
            BaliseSVG::Text => Some(String::from("text")),
            BaliseSVG::TextPath => Some(String::from("textPath")),
            BaliseSVG::Title => Some(String::from("title")),
            BaliseSVG::Tref => Some(String::from("tref")),
            BaliseSVG::Tspan => Some(String::from("tspan")),
            BaliseSVG::Use => Some(String::from("use")),
            BaliseSVG::View => Some(String::from("view")),
            BaliseSVG::Vkern => Some(String::from("vkern")),
            BaliseSVG::Other => None,
        }
    }
}
